frase = str(input("Digite uma frase: "))
fraseLower = (frase.lower())
print("A letra A aparece {} vezes na frase.".format(fraseLower.count("a")))
print("A primeira letra A apareceu na posição {}.".format(fraseLower.find("a")+1))
print("A última letra A apareceu na posição {}.".format(fraseLower.rfind("a")+1))
